#! /bin/sh
set -e

case "$1" in
  configure)
  if [ -f /etc/lightdm/lightdm-gtk-greeter.conf ]; then
    dpkg-divert --add --local --divert /etc/lightdm/lightdm-gtk-greeter.conf.divert --rename /etc/lightdm/lightdm-gtk-greeter.conf
    cp -a /etc/lightdm/lightdm-gtk-greeter-duzeru.conf /etc/lightdm/lightdm-gtk-greeter.conf
  fi
  if [ -f /usr/share/lightdm-gtk-greeter/greeter.ui ]; then
    dpkg-divert --add --local --divert /usr/share/lightdm-gtk-greeter/greeter.ui.divert --rename /usr/share/lightdm-gtk-greeter/greeter.ui
    cp -a /usr/share/lightdm-gtk-greeter/greeter-duzeru.ui /usr/share/lightdm-gtk-greeter/greeter.ui
  fi
esac

#SEGUNDO POSTINT
set -e

if [ "$1" = configure ]; then
  update-alternatives --install /usr/share/lightdm-webkit/themes/default \
    lightdm-webkit-theme /usr/share/lightdm-webkit/themes/webkit 5
fi

#TERCEIRO POSTINT
set -e

if [ "$1" = configure ]; then
  update-alternatives --install /usr/share/lightdm-webkit/themes/default \
    lightdm-webkit-theme /usr/share/lightdm-webkit/themes/dzlock 50
fi


exit 0
