#!/bin/sh
set -e

if [ -f /etc/lightdm/lightdm-gtk-greeter.conf.divert ]; then
  rm -f /etc/lightdm/lightdm-gtk-greeter.conf
  dpkg-divert --local --remove --rename /etc/lightdm/lightdm-gtk-greeter.conf
fi
if [ -f /usr/share/lightdm-gtk-greeter/greeter.ui.divert ]; then
  rm -f /usr/share/lightdm-gtk-greeter/greeter.ui
  dpkg-divert --local --remove --rename /usr/share/lightdm-gtk-greeter/greeter.ui
fi
